services:
  - type: web
    name: berserk-tattoos
    env: node
    rootDir: .
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    autoDeploy: true
    plan: free
